#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist
from sensor_msgs.msg import PointCloud2
import sensor_msgs_py.point_cloud2 as pc2

class ObstacleAvoidance(Node):

    def __init__(self):
        super().__init__('obstacle_avoidance')

        self.cmd_pub = self.create_publisher(Twist, '/cmd_vel', 10)

        self.scan_sub = self.create_subscription(
            PointCloud2,
            '/scan/points',
            self.scan_callback,
            10
        )

        self.timer = self.create_timer(0.1, self.control_loop)

        self.obstacle_front = False

    def scan_callback(self, msg):
        self.obstacle_front = False

        # Leer puntos del LiDAR
        for point in pc2.read_points(msg, field_names=("x", "y", "z"), skip_nans=True):

            x, y, z = point

            # zona frontal (ajustable)
            if 0 < x < 1.0 and abs(y) < 0.3:
                self.obstacle_front = True
                break

    def control_loop(self):

        cmd = Twist()

        if self.obstacle_front:
            # girar
            cmd.linear.x = 0.0
            cmd.angular.z = 0.8
        else:
            # avanzar
            cmd.linear.x = 0.4
            cmd.angular.z = 0.0

        self.cmd_pub.publish(cmd)


def main():
    rclpy.init()
    node = ObstacleAvoidance()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()